language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g bower
  - npm install
script:
  - bower install --production
  - npm run -s build
  - bower install
  - npm run -s test
